// User
export const SIGNUP_NEW_USER = "SIGNUP_NEW_USER";
export const LOGIN_NEW_USER = "LOGIN_NEW_USER";
export const CURRENT_USER = "CURRENT_USER";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const LOG_OUT_USER = "LOG_OUT_USER";